### ISSUE TITLE
Browser theme loading issues

### ISSUE THREAD

**Issue by curlpipe** [Codiscite/peacock#13]
In the lastest commit, it seems that peacock is having issues changing the themes, while they work fine on pages like settings.html, the navbar seems to be stuck in light theme, regardless of the contents in the config.json file. 

Peacock does indeed give an error:
![image](https://user-images.githubusercontent.com/11898833/81934733-5688a080-95e7-11ea-8465-b6d43ba3ffa1.png)
so it seems that somewhere within the renderer.js, there is a bug.

**Comment by spikecodes** [comment]
Thanks for the bug submission! It has now been fixed as of 512ea9e2dd3006a40de82d3c7fdb3f520735c204!
